"""fix foreign keys ondelete

Revision ID: e70f07558bf8
Revises: 86b307124f01
Create Date: 2026-04-11 19:57:44.724074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70f07558bf8'
down_revision: Union[str, Sequence[str], None] = '86b307124f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_batch_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_batch_id_fkey'), 'products', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###
